name: Node.js Auto Publish

on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          #always-auth: true
          #registry-url: https://registry.npmjs.org/
      - uses: wangziling100/AutoPublish@v1.0.0-alpha.16
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

