name: "AutoCI"
on:
  pull_request:
  push:

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: auto-ci
      uses: wangziling100/AutoCI@untagged-b884aacccec5dd7f4560
      with:
        configPath: ./.github/autoCI.config.json
        modulesDir: packages