name: Node.js Auto Publish

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      moduleDir: ${{ steps.ci.outputs.moduleDir}}
      info: ${{ step.ci.outputs.info}}
    steps:
      - uses: actions/checkout@v2
      - name: auto-ci
        id: ci
        uses: wangziling100/AutoCI@v1.0.7
        with:
          configPath: .github/autoci.config.json
          #modulesDir: packages
  publish:
    runs-on: ubuntu-latest
    if: ${{needs.ci.outputs.info=='normal'}}
    if: ${{needs.ci.outputs.info=='publish'}}
    needs: ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          #always-auth: true
          #registry-url: https://registry.npmjs.org/
      - uses: wangziling100/AutoPublish@v1.0.0-alpha.26
        with:
          scope: '@wangziling100'
          strict_error: false
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          #GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

